name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test generated code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate code - docker-compose.yml
        run: make all

      - name: Compare generated code
        run: cmp -s docker-compose.yml tests/test-template.yml
